version: "3.8"

services:
  bancho:
    environment:
      - BUILD_TYPE=Debug
      - HOST=127.0.0.1
      - PORT=13380
      - THREADS=2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE
        - HOST
        - PORT
        - THREADS
    container_name: bancho-cpp
    network_mode: host
    restart: always
